# DEPRECATED: This file has been deprecated and its database configurations are fully merged into the main docker-compose.yml.
#
# You can safely delete this file.
# 
# To run databases only, run:
#   docker-compose up -d
#
# To run databases and all Next.js applications in Docker, run:
#   docker-compose --profile apps up -d
